all: fastq-extract.c
	cc -o fastq-extract fastq-extract.c

install: fastq-extract
	@echo "To install"
	@echo "	Copy fastq-extract to the destination directory (e. g. ~/bin)"
	@echo "	Copy fastq-extract.1 to the manual directory (e. g. ~/share/man/man1)"

