#!/bin/bash
#
#	A protocol for ab-initio protein structure prediction.
#
sequence=$1

sequence=`realpath $sequence`
name=${sequence%.*}
name=${name##*/}


maxmodels=5

myhome=~/work/amelones/script
myhome=`dirname $0`
myhome=`realpath $myhome`

######################################################################
#                                                                    #
# First, generate some (hopefully) realistic models                  #
#                                                                    #
######################################################################

# we will use at this step a set of tools that have proven valid in CASP
# i-tasser
#	(ideally we would like to also run Sparks and RaptorX)
# DNCon2
#	with various methods (confold1, confold2 and unicon3d)
#
# Multicom
#	(ideally we would include Quark, C-Quark and Rosetta as well)
#
# Pfi-Psi-prediction
# Secondary structure prediction
# naïve structures (alpha, beta, coiled-coil, extended, random)

mkdir -p $name
cp $sequence $name
# Try to generate an homology model using I-TASSER inside
# the $name directory
# if the directory does not exist we have not run i-tasser yet
if [ ! -d $name/i-tasser/$name ] ; then
    # if there is not at least one model, try again
    if [ ! -e $name/i-tasser/$name/model1.pdb ] ; then
        cd $name
        i-tasser `basename $sequence`
        cd ..
    fi
fi

# Try to generate an ab-initio model using alphafold inside
# the $name directory
# If alphafold hasn't been run yet there will be no directory
if [ ! -e $name/alphafold/$name ] ; then
    if [ -x ~/contrib/alphafold/bin/alphafold ] ; then
        cd $name
	~/contrib/alphafold/bin/alphafold $sequence
        cd ..
    else
	echo "Not using AlphaFold2 because it is not installed"
        #exit 1
    fi
fi

# NOTE: THIS SHOULD BE A FUNCTION (FOR CLARITY, MOSTLY)'
# dncon2 will create a directory named $name/dncon2 to save its output
# that's why we start it from above $name (no need to enter into it)
if [ ! -d ./$name/dncon2/confold2-$name.dncon2/top-models ] ; then
    echo "Running DNCON2"
    # this will save all the results in "./dncon2/"
    $myhome/dncon2.sh $sequence CONFOLD2
    #$myhome/dncon2.sh $sequence CONFOLD1	# we considered doing these too
    #$myhome/dncon2.sh $sequence UNICON3D	# but they were worse
fi

# the resulting models will be in ./dncon2/confold2-$name.dncon2/top-models
# there may be a large amount of models (100+)
# we will use a quick score function
# first we check if confold2 was run
if [ -d $name/dncon2/confold2-$name.dncon2/ ] ; then
    # remember current position for later and 'cd' to the confold2 directory
    pushd $name/dncon2/confold2-$name.dncon2/		# google this for info
    
    # check if apollo has already been run
    if [ ! -s $name.apollo/top-models.avg ] ; then
	echo "Running apollo on CONFOLD2 top-models"
	$myhome/apollo.sh $sequence top-models
    fi

    # check if apollo run successfully
    if [ ! -e $name.apollo/top-models.avg ] ; then
       echo "ERROR: HORROR: I cannot find apollo scores for any DNCON2+CONFOLD2 model"
       exit 1
    fi

    # let us select the best $maxmodels models produced by CONFOLD2 and 
    # store them named by score order
    if [ ! -e ../models/1.*.pdb ] ; then
	echo "Selecting $maxmodels best CONFOLD2 models"
	mkdir -p ../models
	order=0
	cat $name.apollo/top-models.avg \
	| tail -n+5 \
	| head -n$maxmodels \
	| while read model score ; do
            order=$(( order + 1 ))
            #cp top-models/$model ../models/$order.confold2.$model
	    cp top-models/$model ../models/$order.$model
	done
    fi
    # recover our last saved position and return to it
    popd	# return to where we came from (above $name)
fi

######################################################################
#                                                                    #
# Prepare everything for CABS                                        #
#                                                                    #
######################################################################

# we will work inside $name to keep everything contained in a single directory
pushd $name
if [ ! -d cabs ] ; then 
    mkdir cabs
fi

# add the sequence if not already there
if [ ! -s cabs/`basename $sequence` ] ; then
    cp $sequence cabs
fi

# check if there are any models generated by I-TASSER and copy up to
# $maxmodels to the cabs folder for further refinement
#for i in ((i=1;i<=maxmodels;i++)) ; do
if [ ! -s cabs/1.i-tasser-model1.pdb ] ; then
    echo "Selecting $maxmodels best I-TASSER models"
    END=$maxmodels
    for ((i=1;i<=END;i++)); do
        if [ -s i-tasser/$name/model$i.pdb ] ; then
            # we cannot just copy because i-tasser does not define chain-IDs
	    #cp i-tasser/$name/model$i.pdb cabs/$i.i-tasser-model$i.pdb
            # add chain-ID to models and save them in cabs directory
            cat i-tasser/$name/model$i.pdb \
            | sed -e '/^ATOM  / s/\(.\{21\}\) /\1A/' \
            > cabs/$i.i-tasser-model$i.pdb
        fi
    done
fi

# check if dncon2 generated a contact matrix and, if so, use it with CABS
if [ -s dncon2/$name.rr.raw ] ; then
    cm=$name.rr.raw
    cp dncon2/$cm cabs
else
    echo "ERROR: DNCON2 did not create a Contact Matrix $name.rr.raw"
    exit 1
fi

# check if CONFOLD2 could generate any models and add them for CABS refinement
if [ -d dncon2/models ] ; then
    # the directory exists, so dncon2 did not fail to generate it
    # but it might be empty, let's check if it contains any models
#    if [ "$( ls -A dncon2/models )" ] ; then
#        # yes, copy the models to folder cabs for CABS to use as templates
#	 # NOTE: this will fail because these models lack chain-ID (see below)
#	 cp -v dncon2/models/*.pdb cabs
#    fi
    # this is an alternative approach that gives us more freedom
    for i in `ls -A dncon2/models/*` ; do
        #echo $i
        # add chain-ID to models and save them in cabs directory so that
        # CABS will find them and refine them
        cat $i \
        | sed -e '/^ATOM  / s/\(.\{21\}\) /\1A/' \
        > cabs/`basename $i`
    done
fi



######################################################################
#                                                                    #
# Now do a structure refinement using CABS                           #
#                                                                    #
######################################################################


cd cabs
$myhome/cabscm00.02.sh `basename $sequence` $cm
cd ..

# we are done with CABS, go back to where we came from (above $name)
popd

exit
# This should probably be in the CABS script
#cp */solution-top/*pdb models_unscored
#cp [1-5].*.pdb models_unscored


######################################################################
#                                                                    #
# Now do a structure refinement using UNRES                          #
#                                                                    #
######################################################################



######################################################################
#                                                                    #
# Now do a structure refinement using Rosetta                        #
#                                                                    #
######################################################################



######################################################################
#                                                                    #
# Now do a structure refinement using MARTINI                        #
#                                                                    #
######################################################################



######################################################################
#                                                                    #
# Now do a structure refinement using an atomistic force field       #
#                                                                    #
######################################################################


