#!/bin/bash
#
# NAME
#	gmx_append_trj_steps - append to a trajectory a number of steps 
#
# SYNOPSIS
#	gmx_append_trj_steps [name] [steps]
#
# DESCRIPTION
#	Given a terminated trajectory, with its corresponding input run 
# .tpr and checkpoint .cpt files, expand the existing trajectory for
# the specified number of steps.
#
#	The new trajectory will start from the last checkpoint of the
# previous one.
#
#	Important note: if the number of steps is -1 then the trajectory
# will continue for an infinite amount of time and will need to be
# manually stopped once you consider it long enough.
#
# ARGUMENTS
#	name	- the trajectory base name (without extension)
#	steps	- the number of steps to add to the trajectory
#
# LICENSE:
#
#	Copyright 2023 JOSE R VALVERDE, CNB/CSIC.
#
#	EUPL
#
#       Licensed under the EUPL, Version 1.1 or \u2013 as soon they
#       will be approved by the European Commission - subsequent
#       versions of the EUPL (the "Licence");
#       You may not use this work except in compliance with the
#       Licence.
#       You may obtain a copy of the Licence at:
#
#       http://ec.europa.eu/idabc/eupl
#
#       Unless required by applicable law or agreed to in
#       writing, software distributed under the Licence is
#       distributed on an "AS IS" basis,
#       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#       express or implied.
#       See the Licence for the specific language governing
#       permissions and limitations under the Licence.
#
#	GNU/GPL
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


GMX_APPEND_TRJ_STEPS="GMX_APPEND_TRJ_STEPS"
LIB=`dirname ${BASH_SOURCE[0]}`	# located in our same directory
#LIB=${BASH_SOURCE[0]##*/}
source $LIB/include.bash
include util_funcs.bash

function gmx_append_trj_steps() {
    if ! funusage $# [md_name] [steps] ; then return $ERROR ; fi 
    notecont "$*"

    local name=${1:-md}
    local step=${2:1000}
    local ERR=1
    local trj=''
    
# If you want to extend the trajectory and append it to the existing one the
# process is a little bit different.
# 
# Let's consider a generic simulation that you started using a file named md.tpr.
# 
# The first thing to do is to create a backup of your existing trajectory so that
# in case something goes wrong you will not lose all your data. Backup the entire
# directory.
# 
# Then, you need to use the convert-tpr module to extend the simulation time
# without creating a new tpr file. In other words, the name of the tpr file that
# you create via the -o flag needs to be the same as the one you already used.
# 
# To extend it for an infinite amount of time you can use the -nsteps -1 flag,
# then it will be up to you to stop the simulation when you think you don't need
# additional time.
# 
# gmx_mpi convert-tpr -s md.tpr -nsteps -1 -o md.tpr 
# 
# Now you have a new md.tpr file that you can run for an infinite number of steps.
# 
# To append to the previous files you will need to have all the files generated by
# the previous simulation with the same prefix in the current directory (md.xtc,
# md.edr, md.log, md.trr, md.cpt). Note that you can only append if all the files
# have the same designation.
# 
# Finally, you can run the simulation starting from the last cpt file:
# 
# gmx mdrun -v -deffnm md -cpi md.cpt
# 


    trj="$name"
    
    if [ ! -s "$trj".tpr ] ; then
        warncont "no $trj.tpr"
	return $(( END++ ))
    fi
    if [ ! -s "$trj".cpt ] ; then
        warncont "no $previous.cpt"
	return $(( END++ ))
    fi
    cp "$trj.cpt" "$trj.cpt.sav"
    
    gmx convert-tpr -s "$trj.tpr" -nsteps $steps -o "$trj.tpr"

    gmx mdrun -cpi "$trj.cpt" -deffnm "$trj" -noappend -v
    
}



if [[ $0 == $BASH_SOURCE ]] ; then
    # if we are not being included by other file, then we are being
    # called as an independent program. Set "INCLUDE=yes" to include
    # all the necessary files and do our work.
    # [[ -v VAR ]] tests if a variable is set
    # [[ -z "$VAR" ]] tests if length of $VAR is zero
    LIB=`dirname $0`
    source $LIB/include.bash
    include util_funcs.bash

    gmx_append_trj_steps $*
else
    export GMX_APPEND_TRJ_STEPS
fi
