# Currently seems to relocate chains, moving them, so for now
# this should not be used for multi-chain PDB CG files.

orig=$1
name=${orig%.pdb}
ca=${name}.ca.pdb
USESS='no'	# faster as it does not run PsiPred
#USESS='yes'	# slower but should be better
chains="chains.remo"
capdb="ca.pdb"
cafas="ca.fasta"
cadat="ca.seq.dat"
fixpdb="fix.pdb"
hpdb="h.pdb"
if [ "$USESS" = "yes" ] ; then 
    chains="$chains.ss" 
fi


mkseq=`pwd`/REMO/mkseq.j.pl
remo=`pwd`/REMO/REMO.j.pl

# we will generate two files, one named '.h.pdb' and one named '.fix.pdb'

echo "Extracting CA trace (BB)"
cat $orig | grep ' BB ' | sed -e 's/ BB / CA /g' > $ca

mkdir -p "$chains"
echo "REMARK                                                    " \
> ${name}.fix.pdb
echo "REMARK                                                    " \
> ${name}.h.pdb

for chain in `grep -E "^(ATOM  |HETATM)" $ca | \
	      cut -c 22 | \
              sort | \
              uniq` ; do
    echo "Extracting chain $chain from $ca"
    # check we can actually extract that chain
    if ! grep "^.\{21\}$chain" $ca > "$chains"/${name}_${chain}.$capdb ; then
        echo "ERROR: Something went wrong! Chain ${chain} not extracted"
        rm -f "$chains"/${name}_${chain}.$capdb
    else
        # if the chain was successfully extracted
	    # run REMO on it
        rm -f PRHB Hdd 		# clean old temprorary files if any
        # we can improve the prediction wiith secondary structure data
        # generated by mkseq.pl
        if [ "$USESS" == "yes" ] ; then
		    echo "Computing secondary structure on chain $chain"
            $mkseq "$chains"/${name}_${chain}.$capdb 1
            mv protein.fasta "$chains"/${name}_${chain}.$cafas
            mv seq.dat "$chains"/${name}_${chain}.$cadat
            echo "Running REMO on chain $chain"
			$remo 0 "$chains"/${name}_${chain}.$capdb \
                    "$chains"/${name}_${chain}.$cadat 
        else        
        	echo "Running REMO on chain $chain"
	    	$remo 0 "$chains"/${name}_${chain}.$capdb \
			        "$chains"/${name}_${chain}.$cafasta
        fi
        
        # Now add chain IDs to models generated by REMO
		echo "Adding chain $chain"
        if  [ -e "$chains"/${name}_${chain}.$capdb.fix ] ; then
            # insert chain ID into "fix" PDB file
            cat "$chains"/${name}_${chain}.$capdb.fix \
            | sed "s/^\(.\{21\}\) /\1$chain/g" \
            | grep -E -v "^(END|REMARK)" \
            > "$chains"/${name}_${chain}.ca.$fixpdb
            # and add the chain to the full model
            cat "$chains"/${name}_${chain}.ca.$fixpdb >> ${name}.$fixpdb
        fi
        if  [ -e "$chains"/${name}_${chain}.$capdb.h ] ; then
            # insert chain ID into "h" PDB file
            cat "$chains"/${name}_${chain}.$capdb.h \
            | sed "s/^\(.\{21\}\) /\1$chain/g" \
            | grep -E -v "^(END|REMARK)" \
            > "$chains"/${name}_${chain}.ca.$hpdb
            # and add the chain to the full model
            cat "$chains"/${name}_${chain}.ca.$hpdb >> ${name}.$hpdb
        fi
        if [ -e pPL1 ] ; then mv pPL1 "$chains"/${name}_${chain}.pPL1 ; fi
        rm -f PRHB Hdd 		# clean old temprorary files if any
    fi
done

exit

# renumber atoms 
~/contrib/pdb-tools/pdb_residue-renumber.py ${name}.fix.pdb
~/contrib/pdb-tools/pdb_residue-renumber.py ${name}.h.pdb


# optional minimization
obminimize -ff GAFF ${name}.fix_res-renum.pdb > ${name}.fix.obm.pdb
obminimize -ff GAFF ${name}.h_res-renum.pdb > ${name}.h.obm.pdb
exit
